spring.datasource.url=jdbc:mysql://cinetrack-db:3306/cinetrack_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
# TMDB API Ayarlar?
tmdb.api.key=f1ccd125274e66a555173c702eddaae9
tmdb.api.url=https://api.themoviedb.org/3/search/movie
tmdb.image.base-url=https://image.tmdb.org/t/p/w500